spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 300s
      routes:
        - id: auth_server
          uri: https://example.org
          predicates: # Predicate는 필수값이구나... 안하면 에러남
            - Cookie=mycookie,mycookievalue
        - id: doas_server
          uri: https://example.org
          predicates:
            - Cookie=mycookie,mycookievalue
        - id: linkplus_server
          uri: https://example.org
          predicates:
            - Cookie=mycookie,mycookievalue
        - id: openlounge_server
          uri: https://example.org
          predicates:
            - Cookie=mycookie,mycookievalue