spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 300s
      routes:
        - id: AUTH_SERVER
          uri: https://example.org
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/account/(?<path>.*), /$\{path}
        - id: DOAS
          uri: https://example.org
          predicates:
            - Path=/api/doas/**