server:
  port: 8081
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 300s
      routes:
        - id: test
          uri: https://example.org
          predicates:
            - Path=/foo/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedToknes: 1
        # account server public
#        - id: auth_service_public
#          uri: https://example.org
#          predicates:
#            - Path=/api/signout/**, /api/signin/**, /api/signup/**
#        # account server private
#        - id: auth_service_private
#          uri: https://example.org
#          predicates:
#            - Path=/api/account/**
#          filters:
#            - RewritePath=/account/(?<path>.*), /$\{path}
#        - id: resource-server
#          uri: https://example.org
#          predicates:
#            - Path=/api/resource/**
#          filters:
#            - TokenCheckFilter